config/routes.rb
SwatchesClient::Application.routes.draw do
  resources :swatches, :except => [:show]
  

end

app/models/swatch.rb
class Swatch
  include ActiveModel::Model
  
  attr_accessor :id, :name, :color
  
  validates_presence_of :name, :color
  
  def self.all
    @swatches = []
    @data = JSON.parse(RestClient.get(self._base_url))
    @data.each do |_swatch|
      @swatches << Swatch.new(:id => _swatch['_id'], :name => _swatch['name'], :color => _swatch['color'])
    end
    @swatches
  end
  
  def self.create(params)
    @swatch = Swatch.new(:name => params[:name], :color => params[:color])
    RestClient.post(self._base_url, {:name => @swatch.name, :color => @swatch.color}.to_json)
    @swatch
  end
  
  def self.find(id)
    @data = JSON.parse(RestClient.get(self._base_url + "/#{id}"))
    @swatch = Swatch.new(:id => @data['_id'], :name => @data['name'], :color => @data['color'])
  end
  
  def self.update(id, params)
    @swatch = self.find(id)
    @swatch.name = params[:name]
    @swatch.color = params[:color]
    RestClient.put(self._base_url + "/#{id}", {:name => @swatch.name, :color => @swatch.color}.to_json)
    @swatch
  end
  
  def self.destroy(id)
    @swatch = self.find(id)
    RestClient.delete(self._base_url + "/#{id}")
    @swatch
  end
  
  private
  
  def self._base_url
    Rails.env.production? ? 'http://obscure-spire-1682.herokuapp.com/swatches' : 'http://swatches.dev/swatches'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/swatches_controller.rb
class SwatchesController < ApplicationController
  respond_to :html

  def index
    @swatches = Swatch.all
    respond_with @swatches
  end

  def new
    @swatch = Swatch.new
    respond_with @swatch
  end

  def create
    @swatch = Swatch.create(swatch_params)
    respond_with @swatch, :location => swatches_path
  end

  def edit
    @swatch = Swatch.find(params[:id])
    respond_with @swatch
  end

  def update
    @swatch = Swatch.update(params[:id], swatch_params)
    respond_with @swatch, :location => swatches_path
  end

  def destroy
    @swatch = Swatch.destroy(params[:id])
    respond_with @swatch
  end

  private

  def swatch_params
    params.require(:swatch).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/swatches_helper.rb
module SwatchesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SwatchesClient</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/swatches/edit.html.erb
<%= form_for @swatch, :url => swatch_path(@swatch.id), :method => 'put' do |f| %>
  Name: <%= f.text_field :name %><br />
  Color : <%= f.text_field :color, :type => 'color' %><br />
  <br />
  <%= f.hidden_field :id %>
  <%= f.submit 'Save' %>
<% end %>
<hr>
<%= link_to 'Home', swatches_path %>

app/views/swatches/index.html.erb
<%= link_to 'New Swatch', new_swatch_path %>
<ul>
  <% @swatches.each do |swatch| %>
    <li>
      <%= swatch.name %><br />
      <em><%= swatch.color %></em>
      <%= link_to 'Edit', edit_swatch_path(swatch.id) %>
      |
      <%= link_to 'Delete', swatch_path(swatch.id), :method => 'delete' %>
    </li>
  <% end %>
</ul>

app/views/swatches/new.html.erb
<%= form_for @swatch do |f| %>
  Name: <%= f.text_field :name %><br />
  Color : <%= f.text_field :color, :type => 'color' %><br />
  <br />
  <%= f.submit %>
<% end %>
<hr>
<%= link_to 'Home', swatches_path %>